#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
# What is the value of the first triangle number to have over five hundred divisors?

require 'prime'
i = 1
triangle_number = 0
factors = []

until factors.length > 500
	triangle_number += i
	#puts triangle_number
	factors = (1..triangle_number).to_a.select {|x| triangle_number % x == 0}
	i += 1
end

puts triangle_number

